=== sykp241095/ossinsight/packages/types/schema/query.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "QuerySchema",
  "type": "object",
  "properties": {
    "name": {
      "description": "Query name, default is generated base on the file path.",
      "type": "string"
    },
    "engine": {
      "description": "Template engine.",
      "type": "string",
      "enum": ["legacy", "liquid"]
    },
    "public": {
      "description": "Indicating if the query is public.",
      "type": "boolean",
      "default": false
    },
    "deprecated": {
      "description": "Indicating if the query is deprecated",
      "type": "boolean",
      "default": false
    },
    "description": {
      "description": "Query description for documentation.",
      "type": "string"
    },
    "cacheProvider": {
      "description": "Specify how to implement caching, NORMAL_TABLE are used by default.",
      "enum": ["NORMAL_TABLE", "CACHED_TABLE"]
    },
    "cacheHours": {
      "description": "Cache time in hours, -1 indicates that the query cache will not expire.",
      "type": "number"
    },
    "refreshQueue": {
      "description": "Specify which queue is used to execute prefetch job. The default is MAIN.",
      "type": "string"
    },
    "refreshCron": {
      "description": "The CRON expressions that control when the refresh cache task is executed.",
      "oneOf": [
        {
          "type": "string"
        },
        {
          "$ref": "#/definitions/ConditionalRefreshCrons"
        }
      ]
    },
    "onlyFromCache": {
      "description": "Only return data from the cache.",
      "type": "boolean"
    },
    "params": {
      "description": "Query params declaration.",
      "type": "array",
      "items": {
        "$ref": "#/definitions/Params"
      }
    },
    "persist": {
      "description": "The configuration related to query result persisting.",
      "$ref": "#/definitions/PersistConfig"
    },
    "resultSchema": {
      "description": "Result data schema for description.",
      "$ref": "https://spec.openapis.org/oas/3.0/schema/2021-09-28#/definitions/Schema"
    }
  },
  "additionalProperties": false,
  "required": [
    "cacheHours",
    "params"
  ],
  "definitions": {
    "Params": {
      "type": "object",
      "properties": {
        "name": {
          "description": "URL Search param name for the query.",
          "type": "string"
        },
        "description": {
          "description": "Param description for documentation. If undefined, value in param-descriptions.json would be taken as default",
          "type": "string"
        },
        "type": {
          "description": "Define the parameter type.",
          "type": "string",
          "enum": ["array", "string", "number", "boolean", "integer"]
        },
        "itemType": {
          "description": "Define the array item type.",
          "type": "string",
          "enum": ["string", "number", "boolean", "integer"]
        },
        "maxArrayLength": {
            "description": "Define the max array length.",
            "type": "number",
            "default": 10,
            "minimum": 0
        },
        "column": {
          "description": "Define the parameter corresponding column name.",
          "type": "string"
        },
        "dateRangeTo": {
          "description": "Set in date-range should use that moment as `to` time.",
          "type": "string",
          "enum": ["now", "last-valid-datetime"],
          "default": "last-valid-datetime"
        },
        "replaces": {
          "description": "Define substring in the query sql template. Replacing uses `String.replaceAll`, please make sure the replacing substring is not substring of other texts.",
          "type": "string"
        },
        "template": {
          "description": "Replacing templates, mapped by search value",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "default": {
          "description": "Default input value.",
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        },
        "enums": {
          "description": "Enums for prefetching and validating, default is no prefetching and validating.",
          "oneOf": [
            {
              "description": "Predefined query params name.",
              "type": "string"
            },
            {
              "description": "The allowed values and should be prefetched.",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          ]
        },
        "pattern": {
          "description": "Regular expression for validating parameter value.",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "replaces"
      ]
    },
    "ConditionalHours": {
      "type": "object",
      "properties": {
        "param": {
          "type": "string"
        },
        "on": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "type": "number"
            }
          }
        }
      },
      "required": ["param", "on"],
      "additionalProperties": false
    },
    "ConditionalRefreshCrons": {
      "type": "object",
      "properties": {
        "param": {
          "type": "string"
        },
        "on": {
          "type": "object",
          "patternProperties": {
            ".*": {
              "type": "string"
            }
          }
        }
      },
      "required": ["param", "on"],
      "additionalProperties": false
    },
    "PersistConfig": {
      "type": "object",
      "required": ["tableName", "series", "fields"],
      "properties": {
        "tableName": {
          "description": "The table name of table to persist query result.",
          "type": "string"
        },
        "series": {
          "description": "The series, which is used to identify the item of query result item.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name"],
            "properties": {
              "name": {
                "description": "The name of the series.",
                "type": "string"
              },
              "expression": {
                "description": "The expression of the series value.",
                "type": "string"
              }
            }
          }
        },
        "fields": {
          "description": "The fields, which store the data part of query result item.",
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name"],
            "properties": {
              "name": {
                "description": "The name of the column.",
                "type": "string"
              },
              "expression": {
                "description": "The expression of the series value.",
                "type": "string"
              }
            }
          }
        }
      },
      "additionalProperties": false
    }
  }
}

=== sykp241095/ossinsight/configs/queries/trending-repos/params.json
{
  "public": true,
  "engine": "liquid",
  "description": "Repository trending alternative to https://github.com/trending",
  "cacheHours": -1,
  "refreshCron": {
    "param": "period",
    "on": {
      "past_24_hours": "@daily",
      "past_week": "@daily",
      "past_month": "@daily",
      "past_3_months": "@daily"
    }
  },
  "onlyFromCache": true,
  "persist": {
    "tableName": "mv_trending_repos",
    "series": [
      {
        "name": "dt",
        "expression": "{{#$now}}yyyy-MM-dd{{/$now}}"
      },
      {
        "name": "language",
        "expression": "{{$params.language}}"
      },
      {
        "name": "period",
        "expression": "{{$params.period}}"
      },
      {
        "name": "repo_id",
        "expression": "{{$row.repo_id}}"
      }
    ],
    "fields": [
      {
        "name": "stars"
      },
      {
        "name": "forks"
      },
      {
        "name": "pull_requests"
      },
      {
        "name": "pushes"
      },
      {
        "name": "total_score"
      },
      {
        "name": "contributor_logins"
      }
    ]
  },
  "params": [
    {
      "name": "period",
      "description": "Trending time period.",
      "replaces": "${period}",
      "default": "past_24_hours",
      "enums": [
       "past_24_hours", "past_week", "past_month", "past_3_months"
      ]
    },
    {
      "name": "language",
      "description": "Primary language",
      "replaces": "${language}",
      "default": "All",
      "enums": [
        "All", "JavaScript", "Java", "Python", "PHP", "C++", "C#", "TypeScript", "Shell", "C", "Ruby", "Rust", "Go", "Kotlin", "HCL", "PowerShell", "CMake", "Groovy", "PLpgSQL", "TSQL", "Dart", "Swift", "HTML", "CSS", "Elixir", "Haskell", "Solidity", "Assembly", "R", "Scala", "Julia", "Lua", "Clojure", "Erlang", "Common Lisp", "Emacs Lisp", "OCaml", "MATLAB", "Objective-C", "Perl", "Fortran"
      ]
    }
  ],
  "resultSchema": {
    "type": "object",
    "properties": {
      "repo_id": {
        "type": "number"
      },
      "repo_name": {
        "type": "string"
      },
      "language": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "stars": {
        "type": "number"
      },
      "forks": {
        "type": "number"
      },
      "pull_requests": {
        "type": "number"
      },
      "pushes": {
        "type": "number"
      },
      "total_score": {
        "type": "number"
      },
      "contributor_logins": {
        "type": "string",
        "nullable": true
      },
      "collection_names": {
        "type": "string",
        "nullable": true
      }
    },
    "required": ["repo_id", "repo_name", "language", "description", "stars", "forks", "pull_requests", "pushes", "total_score", "contributor_logins", "collection_names"]
  }
}
